### ISSUE TITLE
Use TOML lists rather than comma separated strings

### ISSUE THREAD

**Issue by johnthagen** [csachs/pyproject-flake8#10]
For a tag such as `extend-ignore`, a more natural TOML API for the user would be that instead of:

```toml
extend-ignore = "E203,E204"
```

Would be:

```toml
extend-ignore = ["E203", "E204"]
```

Behind the scenes, `pyproject-flake8` could add commas as needed as it calls out to `flake8`, but I think it would be cleanest if this was hidden from the user.

This is also more closely to what an actual TOML implementation would look like for `flake8`.

**Comment by d-k-bo** [comment]
As far as I can tell, using arrays (lists) like in your example works fine. However, using a table (dict) for `per-file-ignores` doesn't work in my case.
So instead of
```toml
[tool.flake8.per-file-ignores]
"tests/*" = ["D", "ANN"]
"noxfile.py" = ["D", "ANN"]
```
I have to write
```toml
[tool.flake8]
per-file-ignores = ["tests/*: D, ANN", "noxfile.py: D, ANN"]
```
