### ISSUE TITLE
Pre-commit hook and pyproject-flake8

### ISSUE THREAD

**Issue by MartinGrignard** [csachs/pyproject-flake8#3]
Hi :slightly_smiling_face: 

Thanks for this nice addition to the `flake8` ecosystem!
I'm currently working on a project relying on `pre-commit-config.yaml` to insure consistency in the code style.

Since the default commit hook does not include your package, I tried using the method described [here](https://flake8.pycqa.org/en/latest/user/using-hooks.html):
```yaml
repos:
    # Flake8
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          additional_dependencies: [pyproject-flake8]
```
My config for `flake8` in `pyproject.toml` is:
```toml
[tool.flake8]
ignore = "E203, E266, E501, W503, F403, F401"
exclude = ".git, .mypy_cache, .pytest_cache, build, dist"
max-line-length = 89
max-complexity = 18
select = "B,C,E,F,W,T4,B9"
```
Yet, when running the commit hook, I get:
```
E501 line too long (87 > 79 characters)
```
This means that the configuration is not parsed properly from the `pyproject.toml`.
Do you have any idea to solve this?

Thanks :slightly_smiling_face:

**Comment by MartinGrignard** [comment]
Sorry for the auto-reply, but if someone comes across the same issue, here is a configuration that works. The problem was that the hook used the `flake8` command and not `pflake8`:
```yaml
- repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          entry: pflake8
          additional_dependencies: [pyproject-flake8]
```
